# Generated by Django 4.2.5 on 2023-11-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_category_slug_alter_musician_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['-time_create'], 'verbose_name': 'Музыкант', 'verbose_name_plural': 'Музыканты'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.musician', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-time_create'],
            },
        ),
    ]
