# Generated by Django 4.1.7 on 2023-04-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['-time_create'], 'verbose_name': 'Музыканта', 'verbose_name_plural': 'Музыканты'},
        ),
    ]
