# Generated by Django 4.2.5 on 2023-11-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_musician_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='Post',
        ),
    ]
